# Generated by Django 3.2.6 on 2022-07-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220706_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
